name: Generate Snake

on:
  schedule:
      - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: ShubhamAggarwal0812
          svg_out_path: dist/snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

      - name: Push Snake to README
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
